#ifndef QUEUE_H_INCLUDED
#define QUEUE_H_INCLUDED

//THIS FILE DEFINES THE COMMANDS AVAILABLE IN THE QUEUE INTERFACE
//THEY ARE
//ENQUEUE: ADD A NUMBER TO THE QUEUE
//PRINT: PRINT THE CURRENT QUEUE
//DEQUEUE: DEQUEUES THE OLDEST INPUT AND REMOVES IT FROM THE LIST

#endif // QUEUE_H_INCLUDED
